services:
  spring-app:
    image: adoptopenjdk:17-jre-hotspot
    container_name: spring-app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/your_database_name
      - SPRING_DATASOURCE_USERNAME=your_database_user
      - SPRING_DATASOURCE_PASSWORD=your_database_password
    volumes:
      - ./target/your-spring-app.jar:/app/app.jar
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    command: ["java", "-jar", "/app/app.jar"]

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    ports:
      - "5432:5432"