server:
  port: 8069

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_app
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

app:
  users:
    maxPageSize: 100
  posts:
    maxPageSize: 50

