server:
  port: 8069

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_app
    username: postgres
    password: password
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: e9a64b4fa7f77f
    password: 93d06803ea49c9
    protocol: smtp
    properties.mail.smtp:
      auth: false
      starttls.enable: true

logging.level.org.springframework.security: DEBUG
logging.level.com: INFO

app:
  users:
    maxPageSize: 100
  posts:
    maxPageSize: 50
  comments:
    maxPageSize: 200

  frontend:
    baseUrl: https://localhost:3000
    viewPost: ${frontend.baseUrl}/post/%s
    viewComment: ${frontend.baseUrl}/post/%s/comment/%s

  jwt:
    secret: "8c804c36256e93d041eaa691cfa46e94fa69637edab292f0878f770715619d89687bf5b982e77da2d73246b76ff36bbdb8b26933d5a5993ca144d8532f851a97"

